version: '1'

services:
# This container will run Cypress tests
  cypress:
    image: "cypress/included:9.5.2"
    container_name: cypress

    # We can add any arguments like --browser chrome 
    command: "--config video=false"


    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json

