name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Setup Node

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
    
  cypress:
    runs-on: ubuntu-latest
    name: Cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress
        uses: cypress-io/github-action@v2
        with: 
          start: npm run test


  automerge:
    needs: [cypress, linting]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write    
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}